name: Linux-CI
on:
  push:
    branches: [master]
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build --verbose
      - name: Check
        run: cargo check --verbose
      - name: Clippy
        run: cargo clippy --all-targets --all-features
